spring:
    profiles:
        active: dev
    mail:
        host: smtp.gmail.com
        port: 587
        username: vetmanagerApp@gmail.com  #Replace this field with your Gmail username.
        password: vetManager13App          #Replace this field with your Gmail password.
        protocol: smtp
        tls: true
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.gmail.com
server:
    port: 8083